export const mathProblems = [
    {
        id: 1,
        title: "Suma básica",
        description: "Calcular 2 + 2.",
        difficulty: "Fácil",
        dueDate: "10/05/2025",
        status: "Pendiente",
        mathFormula: "2+2",
        solution: "4",
    },
    {
        id: 2,
        title: "Resta básica",
        description: "Calcular 15 - 7.",
        difficulty: "Fácil",
        dueDate: "11/05/2025",
        status: "Pendiente",
        mathFormula: "15-7",
        solution: "8",
    },
    {
        id: 3,
        title: "Multiplicación básica",
        description: "Calcular 8 × 7.",
        difficulty: "Fácil",
        dueDate: "12/05/2025",
        status: "Pendiente",
        mathFormula: "8*7",
        solution: "56",
    },
    {
        id: 4,
        title: "División con decimales",
        description: "Calcular 7 ÷ 4.",
        difficulty: "Media",
        dueDate: "13/05/2025",
        status: "Pendiente",
        mathFormula: "7/4",
        solution: "1.75",
    },
    {
        id: 5,
        title: "Potencia",
        description: "Calcular 3^4.",
        difficulty: "Media",
        dueDate: "14/05/2025",
        status: "Pendiente",
        mathFormula: "3^4",
        solution: "81",
    },
    {
        id: 6,
        title: "Raíz cuadrada",
        description: "Calcular la raíz cuadrada de 169.",
        difficulty: "Media",
        dueDate: "15/05/2025",
        status: "Pendiente",
        mathFormula: "\\sqrt{169}",
        solution: "13",
    },
    {
        id: 7,
        title: "Límite trigonométrico",
        description: "Calcular \\(\\lim_{x \\to 0} \\frac{\\sin(x)}{x}\\).",
        difficulty: "Difícil",
        dueDate: "16/05/2025",
        status: "Pendiente",
        mathFormula: "\\lim_{x \\to 0} \\frac{\\sin(x)}{x}",
        solution: "1",
    },
    {
        id: 8,
        title: "Derivada",
        description: "Calcular la derivada de \\(f(x) = x^3 + 5x\\).",
        difficulty: "Difícil",
        dueDate: "17/05/2025",
        status: "Pendiente",
        mathFormula: "\\frac{d}{dx}(x^3 + 5x)",
        solution: "3x^2 + 5",
    },
    {
        id: 9,
        title: "Integral básica",
        description:
            "Calcular la integral definida de \\(0\\) a \\(1\\) de \\(e^x\\).",
        difficulty: "Muy Difícil",
        dueDate: "18/05/2025",
        status: "Pendiente",
        mathFormula: "\\int_{0}^{1} e^{x} dx",
        solution: "e - 1",
    },
    {
        id: 10,
        title: "Factorial",
        description: "Calcular \\(10!\\).",
        difficulty: "Muy Difícil",
        dueDate: "19/05/2025",
        status: "Pendiente",
        mathFormula: "10!",
        solution: "3628800",
    },
    {
        id: 11,
        title: "Derivadas de Funciones Compuestas",
        description:
            "Calcular la derivada de funciones compuestas utilizando la regla de la cadena y otras reglas de derivación.",
        difficulty: "Media",
        dueDate: "",
        status: "Completado",
        mathFormula: "\\frac{d}{dx}(2x+1)^5",
        solution: "10(2x+1)^4",
    },
    {
        id: 12,
        title: "Integrales Definidas",
        description:
            "Resolver integrales definidas para calcular el área bajo una curva en un intervalo específico.",
        difficulty: "Media",
        dueDate: "20/05/2025",
        status: "Pendiente",
        mathFormula: "\\int_{0}^{\\pi} \\sin(x)\\,dx",
        solution: "2",
    },
    {
        id: 13,
        title: "Ecuaciones Diferenciales",
        description:
            "Resolver ecuaciones diferenciales de primer orden utilizando el método de separación de variables.",
        difficulty: "Difícil",
        dueDate: "01/04/2025",
        status: "Vencido",
        mathFormula: "\\frac{dy}{dx} = 3y",
        solution: "y = Ce^{3x}",
    },
    {
        id: 14,
        title: "Límites y Continuidad",
        description: "Calcular límites utilizando diferentes técnicas.",
        difficulty: "Media",
        dueDate: "",
        status: "Pendiente",
        mathFormula: "\\lim_{x \\to 0} \\frac{1 - \\cos(x)}{x^2}",
        solution: "1/2",
    },
    {
        id: 15,
        title: "Matrices y Determinantes",
        description:
            "Realizar operaciones con matrices, calcular determinantes y resolver sistemas lineales.",
        difficulty: "Media",
        dueDate: "",
        status: "Completado",
        mathFormula: "\\det\\begin{pmatrix}2 & 3\\\\1 & 4\\end{pmatrix}",
        solution: "5",
    },
    {
        id: 16,
        title: "Series de Taylor",
        description:
            "Calcular la serie de Taylor para aproximar funciones alrededor de un punto.",
        difficulty: "Difícil",
        dueDate: "",
        status: "Pendiente",
        mathFormula: "e^x",
        solution: "1 + x + \\frac{x^2}{2} + \\frac{x^3}{6}",
    },
];
